[git_branch]
symbol = 'ğŸŒ±'

[cmake]
symbol = "ğŸ§¬ "

[c]
symbol = "ğŸ§¬ "
format = 'via [$name $version]($style)'

[docker_context]
symbol = "ğŸ³ "

[nodejs]
symbol = "ğŸ’€ "

[sudo]
style = 'bold red'
symbol = 'ğŸ§™ '
disabled = false

[os.symbols]
Macos = "ğŸ "

[package]
symbol = "ğŸ“¦ "

[zig]
symbol = "ğŸ¦ "

[rust]
symbol = "ğŸ¦€ "

[golang]
symbol = "ğŸ¹ "
